# Generated by Django 4.0.1 on 2022-01-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ChongLangTV', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseName',
            field=models.CharField(default='Unspecified', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='isAdministrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Unspecified', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Unspecified', max_length=16),
        ),
    ]
