# Generated by Django 4.0.1 on 2022-03-05 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ChongLangTV', '0003_course_coursename_user_isadministrator_user_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isAdministrator',
        ),
    ]
