# Generated by Django 4.0.1 on 2022-03-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ChongLangTV', '0004_delete_course_remove_user_isadministrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('postName', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(auto_now=True)),
                ('lastRepliedDate', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyOfPosts',
            fields=[
                ('replyId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1024)),
                ('repliedDate', models.DateTimeField(auto_now=True)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChongLangTV.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Unspecified', max_length=16, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserUserFriendRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationshipFormationDate', models.DateTimeField(auto_created=True)),
                ('userName1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1',
                                                to='ChongLangTV.user')),
                ('userName2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2',
                                                to='ChongLangTV.user')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyOfReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('repliedDate', models.DateTimeField(auto_now=True)),
                ('repliedDaterUsername',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChongLangTV.user')),
                ('repliedPost',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChongLangTV.replyofposts')),
            ],
        ),
        migrations.AddField(
            model_name='replyofposts',
            name='repliedDaterUsername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChongLangTV.user'),
        ),
        migrations.AddField(
            model_name='Post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChongLangTV.user'),
        ),
    ]
