# Generated by Django 4.0.1 on 2022-03-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChongLangTV', '0005_post_replyofposts_remove_user_id_alter_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postId',
        ),
        migrations.RemoveField(
            model_name='replyofposts',
            name='replyId',
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replyofposts',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(default=' ', max_length=1024),
        ),
        migrations.AlterField(
            model_name='post',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='postName',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='replyofposts',
            name='content',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='replyofposts',
            name='repliedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='replyofreply',
            name='content',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='replyofreply',
            name='repliedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useruserfriendrelationship',
            name='relationshipFormationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendDate', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='ChongLangTV.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='ChongLangTV.user')),
            ],
        ),
    ]
