# Generated by Django 4.0.1 on 2022-03-05 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ChongLangTV', '0006_remove_post_postid_remove_replyofposts_replyid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replyofposts',
            name='Post',
        ),
        migrations.RemoveField(
            model_name='replyofposts',
            name='repliedDaterUsername',
        ),
        migrations.RemoveField(
            model_name='replyofreply',
            name='repliedDaterUsername',
        ),
        migrations.RemoveField(
            model_name='replyofreply',
            name='repliedPost',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='ReplyOfPosts',
        ),
        migrations.DeleteModel(
            name='ReplyOfReply',
        ),
    ]
