# Generated by Django 4.0.1 on 2022-03-05 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChongLangTV', '0007_remove_replyofposts_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postName', models.CharField(default=' ', max_length=100)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('lastRepliedDate', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(default=' ', max_length=1024)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChongLangTV.user')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyOfPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=1024)),
                ('repliedDate', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChongLangTV.post')),
                ('repliedDaterUsername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChongLangTV.user')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyOfReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=1024)),
                ('repliedDate', models.DateTimeField(auto_now_add=True)),
                ('repliedDaterUsername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChongLangTV.user')),
                ('repliedPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChongLangTV.replyofposts')),
            ],
        ),
    ]
