# Generated by Django 4.0.1 on 2022-03-21 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChongLangTV', '0008_post_replyofposts_replyofreply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replyofposts',
            old_name='Post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='replyofposts',
            old_name='repliedDaterUsername',
            new_name='repliedUsername',
        ),
        migrations.RenameField(
            model_name='replyofreply',
            old_name='repliedDaterUsername',
            new_name='repliedUsername',
        ),
    ]
